## Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
# Importing numpy
import numpy as np

In [12]:
a = np.array([1,2,3])

In [11]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
print(type(a))  
print(a.shape) 
print(a[0], a[1], a[2]) 
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [6]:
# Create Matrix
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.shape

(2, 3)

In [15]:
print(b[0, 0], b[0, 1], b[1, 0], b[1,2])

1 2 4 6


In [16]:
a = np.zeros((4,5))   # Create an array of all zeros
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
b = np.ones((1,2))    # Create an array of all ones
print(b)

[[1. 1.]]


In [18]:
c = np.full((3,2), 7)  # Create a constant array
print(c)               

[[7 7]
 [7 7]
 [7 7]]


In [19]:
d = np.eye(5)         # Create a 5x5 identity matrix
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
e = np.random.random((3,2))  # Create an array filled with random values
print(e)

[[0.37855296 0.49715065]
 [0.19357983 0.49105254]
 [0.87740113 0.77456867]]


### Array indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [26]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a.shape

(3, 4)

In [85]:
a[:,-1:]

array([[ 4],
       [ 8],
       [12]])

In [80]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [40]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [41]:
x

array([[1, 2],
       [3, 4]])

In [42]:
y

array([[5, 6],
       [7, 8]])

In [43]:
# Elementwise sum
print(x + y)

[[ 6  8]
 [10 12]]


In [44]:
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [45]:
# Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [46]:
# Elementwise Multiplication
print(x * y)

[[ 5 12]
 [21 32]]


In [47]:
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


In [48]:
# Elementwise division
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [49]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [50]:
# Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [51]:
# Matrix Multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [52]:
x

array([[1, 2],
       [3, 4]])

In [53]:
y

array([[5, 6],
       [7, 8]])

In [54]:
# Matrix Multiplication
x@y

array([[19, 22],
       [43, 50]])

In [56]:
print(x.dot(y))
print(np.dot(x, y))
print(np.matmul(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [57]:
x = np.array([[1,2], [3,4]])
print(x) 

print(x.T) 

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [69]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [70]:
x.shape

(4, 3)

In [71]:
v.shape

(3,)

In [72]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
y = x + v

In [74]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [75]:
l1 = [1,2,3]
l2 = [5,6,7]

In [77]:
l1+l2

[1, 2, 3, 5, 6, 7]

In [78]:
l1_n = np.array(l1)
l2_n = np.array(l2)

In [79]:
l1_n+l2_n

array([ 6,  8, 10])