## Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
# Importing numpy
import numpy as np

In [39]:
a = np.array([1, 2, 3])

In [40]:
a

array([1, 2, 3])

In [41]:
type(a)

numpy.ndarray

In [4]:
print(type(a))  
print(a.shape) 
print(a[0], a[1], a[2]) 
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [42]:
# Create Matrix
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
b.shape

(2, 3)

In [7]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [45]:
a = np.zeros((4,5))   # Create an array of all zeros
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
b = np.ones((1,2))    # Create an array of all ones
print(b)

[[1. 1.]]


In [47]:
c = np.full((3,2), 7)  # Create a constant array
print(c)               

[[7 7]
 [7 7]
 [7 7]]


In [49]:
d = np.eye(5)         # Create a 2x2 identity matrix
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
e = np.random.random((3,2))  # Create an array filled with random values
print(e)

[[0.02192689 0.25103421]
 [0.54672923 0.66219142]
 [0.33598181 0.39853581]]


In [53]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

### Array indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a.shape

(3, 4)

In [60]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [16]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [61]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [62]:
x

array([[1, 2],
       [3, 4]])

In [63]:
y

array([[5, 6],
       [7, 8]])

In [64]:
# Elementwise sum
print(x + y)

[[ 6  8]
 [10 12]]


In [65]:
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [66]:
# Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [67]:
# Elementwise Multiplication
print(x * y)

[[ 5 12]
 [21 32]]


In [68]:
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


In [69]:
# Elementwise division
print(x / y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [70]:
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [71]:
# Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [72]:
# Matrix Multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [73]:
x

array([[1, 2],
       [3, 4]])

In [74]:
y

array([[5, 6],
       [7, 8]])

In [79]:
# Matrix Multiplication
x@y

array([[19, 22],
       [43, 50]])

In [75]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [80]:
x = np.array([[1,2], [3,4]])
print(x) 

print(x.T) 

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [82]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [83]:
x.shape

(4, 3)

In [84]:
v.shape

(3,)

In [38]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
y = x + v

In [37]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [85]:
l1 = [1,2,3]
l2 = [5,6,7]

In [86]:
l1+l2

[1, 2, 3, 5, 6, 7]

In [87]:
l1_n = np.array(l1)
l2_n = np.array(l2)

In [88]:
l1_n+l2_n

array([ 6,  8, 10])

In [95]:
x = np.array([[1,2,3,4,6,7]])

In [96]:
x.shape

(1, 6)

In [101]:
x_T = x.T

In [102]:
x_T

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7]])

In [103]:
x.shape

(1, 6)

In [104]:
x = np.array([[1,2,3],[4,5,6]]).T

In [105]:
x

array([[1, 4],
       [2, 5],
       [3, 6]])